config/routes.rb
Rails.application.routes.draw do
  resources :pictures 
  root 'pictures#index'

end

app/models/picture.rb
class Picture < ActiveRecord::Base
  scope :newest_first, -> { order("created_at DESC") }
  scope :most_recent_five, -> { newest_first.limit(5) }

  def self.created_before(time)
    where("created_at < ?", time)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController

	def index
		@pictures = Picture.most_recent_five
	end

	def new
	end

	def create
		@picture = Picture.new(picture_params)

		@picture.save
		redirect_to @picture
	end

  def show
    @picture = Picture.find(params[:id])
  end

	def edit
		@picture = Picture.find(params[:id])
	end

	def update
    @picture = Picture.find(params[:id])

    if @picture.update_attributes(picture_params)
      redirect_to @picture
    else
      render :edit
    end
	end

  def destroy
    @picture = Picture.find(params[:id])
    @picture.destroy
    redirect_to root_path
  end

	private

	def picture_params
		params.require(:picture).permit(:title, :artist, :url)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Photogur</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pictures/_form.html.erb
_form.html.erb

app/views/pictures/edit.html.erb
<h1><%= @picture.title %></h1>
<%= link_to '//Home', root_path %> | <%= link_to '//View', picture_path %>
<%= form_for @picture do |f| %>
<p>
	<%= f.label :title %>
	<%= f.text_field :title %>
</p>

<p>
	<%= f.label :artist %>
	<%= f.text_field :artist %>
</p>

<p>
	 <%= f.label :url %>
	 <%= f.text_field :url %>
</p>
<p>
  <%= f.submit %>
</p>

<% end %>

app/views/pictures/index.html.erb
<h1>Pictures(<%= @pictures.length %>)</h1>
<%= link_to '//New Photo', new_picture_path %>
<hr>
  <% @pictures.each do |pic| %>

<h2><%= pic.title %></h2>

<p>
  Artist: <strong><%= pic.artist %></strong> | <%= link_to '//Edit', edit_picture_path(pic) %> |  <%= link_to '//View', picture_path(pic) %>
</p>

<p>
  <img src="<%= pic.url %>" />
</p>
<hr>
<% end %>

<hr>
<h1>Older Pictures:(<%= Picture.created_before(1.month.ago).count %>)</h1>
<% Picture.created_before(1.month.ago).each do |pic| %>
  <p>
    Artist: <strong><%= pic.artist %></strong> | <%= link_to '//Edit', edit_picture_path(pic) %> |  <%= link_to '//View', picture_path(pic) %>
  </p>

  <p>
    <img src="<%= pic.url %>" />
  </p>
  <hr>
<% end %>

app/views/pictures/new.html.erb
<h1>Add a new picture!</h1>
<%= link_to '//Home', root_path %>

<%= form_for :picture, url: pictures_path do |f| %>
	<p>
		<%= f.label :title %>
		<%= f.text_field :title %>
	</p>

	<p>
		<%= f.label :artist %>
		<%= f.text_field :artist %>
	</p>

	<p>
		<%= f.label :url %>
		<%= f.text_field :url %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/pictures/show.html.erb
<h1><%= @picture.title %></h1>
<p>
  Artist: <strong><%= @picture.artist %></strong> | <%= link_to '//Home', root_path %> | <%= link_to '//Edit', edit_picture_path %> | <%= link_to '//Delete',  @picture, method: :delete, :data => {confirm: "Are you sure you want to delete this picture?"} %>
</p>

<p>
  <img src="<%= @picture.url %>" alt="It's not here...">
</p>